### ISSUE TITLE
Checkout Page

### ISSUE THREAD

**Issue by Garrett-Bodley** [larkinds/recurse-randomice#29]
## Overview

Parent issue for all issues related to the Checkout Page

## Action Items

- [ ] Cart Summary component
  - [ ] [Checkout Cart Item](https://github.com/larkinds/recurse-randomice/issues/21)
  - [ ] [Cart Summary Header](https://github.com/larkinds/recurse-randomice/issues/26)
  - [ ] Cart Price-Total
- [ ] [Assemble the Cart Items and Price-Total into a card/panel](https://github.com/larkinds/recurse-randomice/issues/27)
- [ ] [Account Summary Component](https://github.com/larkinds/recurse-randomice/issues/28)
- [ ] Communicate with the backend when submitting the cart
- [ ] Communicate with the backend when an order is submitted

**Stretch**:
* Stripe integration

## Resources/Instructions

[Design Page](https://www.notion.so/Checkout-47d2c4a56ebe468eb63deb65c4d4f1f6)
