### ISSUE TITLE
Cart Summary Component

### ISSUE THREAD

**Issue by Garrett-Bodley** [larkinds/recurse-randomice#30]
## Overview

A general organizing Issue for the Cart Summary Component

## Action Items

- [x] [Cart Summary Header](https://github.com/larkinds/recurse-randomice/issues/26)
- [ ] [Checkout Item Component](https://github.com/larkinds/recurse-randomice/issues/21)
- [ ] [Cart Price Total](https://github.com/larkinds/recurse-randomice/issues/27)

## Resources/Instructions

[Design Page](https://www.notion.so/Checkout-47d2c4a56ebe468eb63deb65c4d4f1f6)
