### ISSUE TITLE
Create and populate the Cart modal

### ISSUE THREAD

**Issue by pearlescence-m** [larkinds/recurse-randomice#4]
**Overview**

We need an Cart modal so the user can view the the items in the Cart when clicking on the Cart icon.

**Action Items**

- [ ] Create the modal
- [ ] Get the 'Close' button and add it to the modal #1 
- [ ] Get the Item List and add it to the modal #7 
- [ ] Add a summary/total price information
- [ ] Get the 'Checkout' button and add it to the modal #5 

**Resources/Instructions**
- [Design in Notion](https://www.notion.so/Cart-ff19e760e2f34a9ab5eefa224897d3e5)
